### ISSUE TITLE
Files in config/stack-to-nearby-chests/locked-slots use IP addresses of servers

### ISSUE THREAD

**Issue by armuell** [xiaocihua/stack-to-nearby-chests#10]
I feel like using an ip address for a file name that lives in the config directory is not a good idea. Pack makers will often include the config directory in packs. Not sure if using some other identifier is possible (world uuid or some non ip related info from server.dat maybe) but it would be appreciated.

**Comment by xiaocihua** [comment]
Thanks for your feedback! I can't find any other identifier that can replace the ip address. World UUID is not a vanilla feature. Probably the only solution is to move these files out of the config directory.

**Comment by armuell** [comment]
Why not just use world name? You would need to make sure to remove unsafe filename characters (vanilla has to already do this) and do the thing where you add a "...(1)" and so on to the file name for people that roll seeds and have a bunch of  "New World" saves. I know the Minihud mod uses world names for config files and I've used one or two other mods in the past that I think did a similar thing (one mod was a little different, they had one config file with different objects/arrays inside using different world names) but I can't think of their names right now. Obviously this doesn't work if someone renames their world but that could happen if someone's server got a new ip address so probably not important.

Alternatively you could maybe use the world seed. People can have multiple worlds with the same seed (but maybe that's an edge case that you don't need to worry about?). 

Worse case you could take the ip address and like hash/encrypt it to obfuscate the ip. 

I have no idea why you decided to reopen this card but I got the notif and saw the help wanted tag. Hope you've been well the last 3 years lol

**Comment by xiaocihua** [comment]
Thank you for the suggestions!

As far as I know, the client cannot get the world name of a server. Minihud also uses IP addresses for servers. You also cannot get the seed of a server if you are not an operator (the command /seed requires a permission level of 2 in multiplayer). I also do not want to create files under the root directory of an instance or the user's home directory. The best solution for now is to obfuscate the IP address, as you suggested.
