### ISSUE TITLE
Tooltip conflict with PlayerEX

### ISSUE THREAD

**Issue by ChromaPIE** [xiaocihua/stack-to-nearby-chests#11]
Texts in the tooltip box overlap upon clicking the Attributes and Combat tab in the inventory GUI, which are provided by PlayerEX. This will remain until you go back to the inventory tab. In another word the tooltip will remain cursed in the GUIs of the mentioned tabs.

Moreover you can see from the following screenshots that icons in REI overlay (EMI might have the same problem too) is blocking the quick stack and restock button. You are able to click them though but it's still a problem. Anyway it's not the main issue and I'm not sure if the problem is on your side.

<img src="https://user-images.githubusercontent.com/56111366/218636591-f8454996-dcb4-4090-9bfe-57436f004bb7.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/56111366/218636688-683270f6-8e92-49f4-bb25-1ecceb47c0c6.png" width="40%" height="40%">

If there's more info that needs to be here please let me know.

**Comment by xiaocihua** [comment]
Thank you @ChromaPIE ! The first issue you mentioned will be fixed in the next version.

For the second issue, you can change the position of those two buttons in the latest 0.2.6 version, or just hide them and use shortcut keys instead.

**Comment by xiaocihua** [comment]
Fixed in 0.2.7.
