### ISSUE TITLE
The favorite item hotkey randomly breaks for the current game session

### ISSUE THREAD

**Issue by Essermark** [xiaocihua/stack-to-nearby-chests#2]
The favorite item hotkey stops working at (seemingly) random times, restarting the game fixes this.

**Comment by xiaocihua** [comment]
Sorry for the late reply. I am trying to reproduce this issue. What other mods did you use?

**Comment by xiaocihua** [comment]
I tried to fix the bug and released a new version, you can download it on the release page.

**Comment by Essermark** [comment]
Thanks for the update! I'll test this when I can.

**Comment by Essermark** [comment]
Looks like it's fixed 👍
