### ISSUE TITLE
[feature request] add support for inventoryprofilesnext favorite

### ISSUE THREAD

**Issue by EnderMelody** [xiaocihua/stack-to-nearby-chests#20]
could you please add the option to use inventoryprofilesnext's favorite system instead so we dont have to use multiple mods with a favorite system.

**Comment by xiaocihua** [comment]
I am sorry I didn't reply sooner.

The latest version [0.5.0](https://github.com/xiaocihua/stack-to-nearby-chests/releases/tag/mc1.20.2-0.5.0) adds an option to turn on/off the favorite system and disables quick stacking of items in slots locked by Inventory Profiles Next.

**Comment by EnderMelody** [comment]
much appreciated, thank you!
