### ISSUE TITLE
Persistent favorited items in inventory

### ISSUE THREAD

**Issue by Felisinnn** [xiaocihua/stack-to-nearby-chests#25]
I'm not sure if this is a bug, or an intended feature. Favourited items do not stay favourited after leaving and reentering a world. 

Version: 0.5.0 for Minecraft 1.20 - 1.21
Loader: Fabric Loader 0.14.24
Minecraft 1.20.1

Mod list: 
![Captura de pantalla 2023-11-13 194543](https://github.com/xiaocihua/stack-to-nearby-chests/assets/150624164/2a29e625-15eb-41d5-86ef-807475111588)
![Captura de pantalla 2023-11-13 194513](https://github.com/xiaocihua/stack-to-nearby-chests/assets/150624164/8d1934f8-9261-49d9-9b9d-588e73b646d3)

**Comment by xiaocihua** [comment]
Hi @Felisinnn !

Please upload the logs of when you left and joined the world.

**Comment by xiaocihua** [comment]
Tried to fix in [version 0.5.1](https://github.com/xiaocihua/stack-to-nearby-chests/releases/tag/mc1.20.1-0.5.1). If the problem occurs again, please test with only this mod enabled.

**Comment by xiaocihua** [comment]
Thank you for your help! The new [version 0.5.2](https://github.com/xiaocihua/stack-to-nearby-chests/releases/tag/mc1.20.1-0.5.2) has fixed the compatibility issue. We appreciate your feedback and support.
