### ISSUE TITLE
Any Backport Plan for Those Popular Versions

### ISSUE THREAD

**Issue by lemorage** [xiaocihua/stack-to-nearby-chests#27]
I have been looking for such a mod for years. Thank you for developing such a mod in Minecraft. Just dropped by and want to see if there are future plans to backport some old popular Minecraft versions, like 1.16.5, etc.

**Comment by xiaocihua** [comment]
Hello @lemorage ! I’m glad to hear that you like our mod. Unfortunately, I don’t have time to backport our mod to older versions of Minecraft. I’m sorry for any inconvenience this may cause you.

**Comment by lemorage** [comment]
Ah, fair enough. Anyway, thanks a bunch for the mod! It's seriously awesome.
