### ISSUE TITLE
The action was interrupted, reason: Timed out

### ISSUE THREAD

**Issue by aMazeInRunar** [xiaocihua/stack-to-nearby-chests#29]
Hi, I have a pretty big list of mods. So I don't even know where to start looking for the issue. But when I press the button. it tells me the same thing every single time. Any ideas of what it could be? 
![image](https://github.com/xiaocihua/stack-to-nearby-chests/assets/56029443/5f345dcf-7b4e-4896-a6de-b1d2e76d75b9)
![image](https://github.com/xiaocihua/stack-to-nearby-chests/assets/56029443/66b2461c-9f98-4c6f-8451-d71b55985591)
I'll try removing some of the other inventory related mods, but maybe you know which one of these has a known issue with this mod. 
Thanks in advance, and don't feel obliged to help. Thanks for the mod, I love it =)

**Comment by aMazeInRunar** [comment]
Alright, did some testing. Turns out its just the config range thats making it act like this. Not sure how to make the radius bigger.

**Comment by xiaocihua** [comment]
I appreciate you testing it. Increasing the block reach distance on the client will result in this issue because the server will check the distance between the player and the chest block when it receives the open chest action. I'm trying to find a solution for this issue.

**Comment by Duox29** [comment]
same problems. works fine on singleplayer

**Comment by brend2b** [comment]
Encountering same issue. Minecraft 1.21.4, Fabric Loader 0.16.10, Fabric API 0.118.0.

No other mods. Mods folder contains Fabric API and stack-to-nearby-chests-mc1.21.4-0.5.12

Other players on server have no issue

**Comment by brend2b** [comment]
> Encountering same issue. Minecraft 1.21.4, Fabric Loader 0.16.10, Fabric API 0.118.0.
> 
> No other mods. Mods folder contains Fabric API and stack-to-nearby-chests-mc1.21.4-0.5.12
> 
> Other players on server have no issue

fixed it by changing search interval to 10. I'd raise it higher if still encountering problems
