### ISSUE TITLE
The favourite item hotkey "triggers" outside the inventory

### ISSUE THREAD

**Issue by ShaneTRS** [xiaocihua/stack-to-nearby-chests#3]
When pressing the combination set for "favourite item" outside of the inventory, it cancels the interaction that would normally occur (and does nothing).

For example, setting it to `alt` + `right click` would prevent a player from shooting their bow while holding `alt`.

**Comment by xiaocihua** [comment]
Fixed in [0.2.3](https://github.com/xiaocihua/stack-to-nearby-chests/releases/tag/0.2.3). Thank you @ShaneTRS !
