### ISSUE TITLE
[Bug] BetterEnd/Nether and Iron Chests: Restocked

### ISSUE THREAD

**Issue by INooBTooMuch** [xiaocihua/stack-to-nearby-chests#32]
Minecraft Version : 1.19.2
Fabric Version : 0.15.10
Mod Version : 0.5.4

Stacking or Restocking doesn't work if any of the wanted items are in one of these mods' chests [BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend), [BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether), [Iron Chests: Restocked](https://www.curseforge.com/minecraft/mc-mods/ironchests)

**Comment by xiaocihua** [comment]
Hello @INooBTooMuch !

You need to add these mods' chests to the "Stacking Targets" and "Restocking Sources" lists in the mod options.

**Comment by INooBTooMuch** [comment]
`"betterend:tenanea_chest",
"betterend:mossy_glowshroom_chest",
"betterend:pythadendron_chest",
"betterend:end_lotus_chest",
"betterend:lacugrove_chest",
"betterend:dragon_tree_chest",
"betterend:helix_tree_chest",
"betterend:umbrella_tree_chest",
"betterend:jellyshroom_chest",
"betternether:rubeus_chest",
"betterend:lucernia_chest",
"betternether:nether_reed_chest",
"betternether:stalagnate_chest",
"betternether:willow_chest",
"betternether:wart_chest",
"betternether:chest_of_drawers",
"betternether:crimson_chest",
"betternether:warped_chest",
"betternether:mushroom_fir_chest",
"betternether:nether_mushroom_chest",
"betternether:anchor_tree_chest",
"betternether:nether_sakura_chest",
"ironchests:diamond_chest",
"ironchests:iron_chest",
"ironchests:gold_chest",
"ironchests:crystal_chest",
"ironchests:copper_chest",
"ironchests:dirt_chest",
"ironchests:obsidian_chest",
"ironchests:netherite_chest"`
      
This is what I added for the chests in the stacking and restocking sources and it works.
I saw that you already have charm chests included.

**Comment by xiaocihua** [comment]
Thank you very much！

**Comment by xiaocihua** [comment]
Thank you very much!
