### ISSUE TITLE
 X/Y position problem in creative inventory

### ISSUE THREAD

**Issue by Xsogon** [xiaocihua/stack-to-nearby-chests#34]
![Screenshot 2024-05-16 023145](https://github.com/xiaocihua/stack-to-nearby-chests/assets/98281821/6854ef40-9710-499a-95a9-10dfd35da0aa)
![Screenshot 2024-05-16 022835](https://github.com/xiaocihua/stack-to-nearby-chests/assets/98281821/d9fca843-1113-4e45-9121-7c06986e959e)

When moving the X/Y positions of the buttons so that they are in the inventory, when switching to creative mode they are out of place and covering slots. Having an option in the mod menu to disable it in creative mode could solve this.

(I am using texture pack for the icons)

**Comment by xiaocihua** [comment]
Thank you for your suggestion! I've added this option in [the latest version](https://github.com/xiaocihua/stack-to-nearby-chests/releases).
