### ISSUE TITLE
[compatibility request] unofficial sophisticated storage mod

### ISSUE THREAD

**Issue by McBlob** [xiaocihua/stack-to-nearby-chests#35]
https://modrinth.com/mod/sophisticated-storage-(unofficial-fabric-port)
I already asked the creator of the storage mod if he could maybe add support as tbh i think its more an issue on his end, but it seems like its gonna take a while so i wanted to ask if you could add support. Trying to add it in "Stacking Targets" doesn't do anything and the names are a bit messed up
![image](https://github.com/xiaocihua/stack-to-nearby-chests/assets/71903882/e9e93e4a-3304-4e1f-8916-eb4a5076480e)

**Comment by xiaocihua** [comment]
Fixed in [0.5.8](https://github.com/xiaocihua/stack-to-nearby-chests/releases?q=0.5.8). Thank you for your collaboration.

**Comment by ALpHa44050** [comment]
> Fixed in [0.5.8](https://github.com/xiaocihua/stack-to-nearby-chests/releases?q=0.5.8). Thank you for your collaboration.

I am want it to 1.21.1
