### ISSUE TITLE
not working with my set of mods. 

### ISSUE THREAD

**Issue by yetyman** [xiaocihua/stack-to-nearby-chests#4]
Hello, I am using your pack in a 1.19.2 world. i am using REI and a trash slot mod, which would both affect my inventory HUD, but otherwise i'm not sure what could be interfering.

your mods buttons do not appear at all in my HUD. and the shortcut in your readme doesn't do anything for me. your mod comes up in my mods list as working, but no keybindings are available in my game's controls menu.

your buttons do not show up if i disable the trash slot mod.

here's my mod list with a bunch of mods
https://pastebin.com/MMav1HT9

and here's my logs(but i don't see anything in particular that references errors with this pack)
https://pastebin.com/K2DYC2kP

I would really love to have your packs functionality if you have any ideas what might be wrong.
do you have any recommendations? 
(P.S. i am a java developer but have not touched Minecraft modding/debugging, so let me know if i can get you any additional information)

**Comment by yetyman** [comment]
here is a list of the mods from the folder with their version numbers et al. are you wanting a zip of all of them?
https://pastebin.com/2TKBXjSr

here's a zip
https://drive.google.com/file/d/1tGrieMAKrAku3ZTcjY_Gzvbda8i5-maV/view?usp=sharing

here's a new attempt to upload my logs. this is startup, world load, and opening my inventory.
https://pastebin.com/nQZq0Zjw

**Comment by yetyman** [comment]
pastebin doesn't like log dumps apparently.
here's an upload of my logs
https://drive.google.com/file/d/1UBvslPFN_89cL6VlF5d2mPnfg2TaNTB6/view?usp=sharing

**Comment by xiaocihua** [comment]
This is a Fabric mod so it does not support Forge. I plan to make a Forge version.

You can use [Quickstack](https://www.curseforge.com/minecraft/mc-mods/quickstack) instead. It's a Forge mod provides quickstack functionality. Unlike my mod, it needs to be installed on both the server and client to work.

**Comment by yetyman** [comment]
Thank you! Darn, i thought i was pretty careful about only grabbing forge mods. I guess I'll grab quick stack for now.
