### ISSUE TITLE
Sound effect when highlighting slot

### ISSUE THREAD

**Issue by Disketaa** [xiaocihua/stack-to-nearby-chests#45]
A little touch to make user experience a bit prettier. Just a sound when you favoriting an item and when unfavoriting

**Comment by Disketaa** [comment]
There no sound at all, when you picking up an item from trash slot by the way

**Comment by xiaocihua** [comment]
Added in [0.5.11](https://github.com/xiaocihua/stack-to-nearby-chests/releases/tag/mc1.21.3-0.5.11). Thank you for your suggestion!

If this mod conflicts with the mod providing the trash slot, please let me know the name of that mod.
