### ISSUE TITLE
[Bug] Crashing when using the inventory button

### ISSUE THREAD

**Issue by DanMeadWasTaken** [xiaocihua/stack-to-nearby-chests#8]
So, not sure if this may be a conflict with inventory tabs or something but anytime i try to use the "stack to nearby" inventory button, the whole client crashes, doesn't seem to matter if it's on server or single player.

https://mclo.gs/YTZrpDf

**Comment by DanMeadWasTaken** [comment]
thank you for the solution! i hope ya come up with something eventually though

**Comment by xiaocihua** [comment]
Smooth Swapping mod after 0.8.1 no longer conflicts with this mod.
